import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

// Generated by `pnpm migrate:create challenges`, then edited by hand in `down` only: the generated
// version dropped the payload_locked_documents_rels constraints after `DROP TABLE ... CASCADE` had
// already removed them, so the rollback failed. `IF EXISTS` makes it work.

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TABLE "challenges_videos" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"title" varchar NOT NULL,
  	"youtube_url" varchar,
  	"published_at" timestamp(3) with time zone,
  	"retro_worked" varchar,
  	"retro_dropped" varchar,
  	"retro_change" varchar
  );
  
  CREATE TABLE "challenges" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"slug" varchar NOT NULL,
  	"start_date" timestamp(3) with time zone NOT NULL,
  	"time_zone" varchar DEFAULT 'Asia/Almaty' NOT NULL,
  	"duration_days" numeric DEFAULT 90 NOT NULL,
  	"daily_minutes" numeric DEFAULT 90 NOT NULL,
  	"block_days" numeric DEFAULT 15 NOT NULL,
  	"is_public" boolean DEFAULT false,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "challenges_locales" (
  	"title" varchar NOT NULL,
  	"rules" jsonb,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  
  CREATE TABLE "challenge_days" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"challenge_id" integer NOT NULL,
  	"day_number" numeric NOT NULL,
  	"minutes" numeric NOT NULL,
  	"notes" varchar,
  	"closed_at" timestamp(3) with time zone,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "challenges_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "challenge_days_id" integer;
  ALTER TABLE "challenges_videos" ADD CONSTRAINT "challenges_videos_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."challenges"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "challenges_locales" ADD CONSTRAINT "challenges_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."challenges"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "challenge_days" ADD CONSTRAINT "challenge_days_challenge_id_challenges_id_fk" FOREIGN KEY ("challenge_id") REFERENCES "public"."challenges"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "challenges_videos_order_idx" ON "challenges_videos" USING btree ("_order");
  CREATE INDEX "challenges_videos_parent_id_idx" ON "challenges_videos" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "challenges_slug_idx" ON "challenges" USING btree ("slug");
  CREATE INDEX "challenges_is_public_idx" ON "challenges" USING btree ("is_public");
  CREATE INDEX "challenges_updated_at_idx" ON "challenges" USING btree ("updated_at");
  CREATE INDEX "challenges_created_at_idx" ON "challenges" USING btree ("created_at");
  CREATE UNIQUE INDEX "challenges_locales_locale_parent_id_unique" ON "challenges_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "challenge_days_challenge_idx" ON "challenge_days" USING btree ("challenge_id");
  CREATE INDEX "challenge_days_updated_at_idx" ON "challenge_days" USING btree ("updated_at");
  CREATE INDEX "challenge_days_created_at_idx" ON "challenge_days" USING btree ("created_at");
  CREATE UNIQUE INDEX "challenge_dayNumber_idx" ON "challenge_days" USING btree ("challenge_id","day_number");
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_challenges_fk" FOREIGN KEY ("challenges_id") REFERENCES "public"."challenges"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_challenge_days_fk" FOREIGN KEY ("challenge_days_id") REFERENCES "public"."challenge_days"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "payload_locked_documents_rels_challenges_id_idx" ON "payload_locked_documents_rels" USING btree ("challenges_id");
  CREATE INDEX "payload_locked_documents_rels_challenge_days_id_idx" ON "payload_locked_documents_rels" USING btree ("challenge_days_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "challenges_videos" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "challenges" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "challenges_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "challenge_days" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "challenges_videos" CASCADE;
  DROP TABLE "challenges" CASCADE;
  DROP TABLE "challenges_locales" CASCADE;
  DROP TABLE "challenge_days" CASCADE;
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_challenges_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_challenge_days_fk";
  
  DROP INDEX "payload_locked_documents_rels_challenges_id_idx";
  DROP INDEX "payload_locked_documents_rels_challenge_days_id_idx";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "challenges_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "challenge_days_id";`)
}
