/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    changelog: Changelog;
    'waitlist-signups': WaitlistSignup;
    challenges: Challenge;
    'challenge-days': ChallengeDay;
    'slot-types': SlotType;
    programs: Program;
    'task-pool': TaskPool;
    'program-plan-items': ProgramPlanItem;
    enrollments: Enrollment;
    'auth-codes': AuthCode;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      enrollments: 'enrollments';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    changelog: ChangelogSelect<false> | ChangelogSelect<true>;
    'waitlist-signups': WaitlistSignupsSelect<false> | WaitlistSignupsSelect<true>;
    challenges: ChallengesSelect<false> | ChallengesSelect<true>;
    'challenge-days': ChallengeDaysSelect<false> | ChallengeDaysSelect<true>;
    'slot-types': SlotTypesSelect<false> | SlotTypesSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    'task-pool': TaskPoolSelect<false> | TaskPoolSelect<true>;
    'program-plan-items': ProgramPlanItemsSelect<false> | ProgramPlanItemsSelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    'auth-codes': AuthCodesSelect<false> | AuthCodesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ru') | ('en' | 'ru')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'ru';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Owner = full admin access. To add a student, use "Invite a student" above the users list.
   */
  role: 'owner' | 'student';
  name?: string | null;
  invitedAt?: string | null;
  locale?: ('ru' | 'en') | null;
  addressForm?: ('ty' | 'vy') | null;
  enrollments?: {
    docs?: (number | Enrollment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Программа ученика после теста уровня. Назначайте со страницы ученика (Users → ученик).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: number;
  student: number | User;
  placement: {
    test: 'murad' | 'ielts' | 'toefl' | 'cambridge' | 'duolingo' | 'pte' | 'efset' | 'other';
    /**
     * Вводится вручную, без автоматического пересчёта.
     */
    cefr: 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';
    takenAt: string;
    testName?: string | null;
    scoreText?: string | null;
    exam?: ('KET' | 'PET' | 'FCE' | 'CAE' | 'CPE') | null;
    score?: number | null;
    note?: string | null;
  };
  /**
   * Только опубликованные. Сменить можно, пока ученик не начал.
   */
  program: number | Program;
  /**
   * Начинает ученик («Начать»). Владелец может только завершить.
   */
  status: 'assigned' | 'active' | 'paused' | 'finished';
  assignedAt?: string | null;
  /**
   * День 1 — день, когда ученик нажал «Начать».
   */
  startDate?: string | null;
  timezone?: string | null;
  /**
   * Паузы появятся в истории 017.
   */
  pauses?:
    | {
        from: string;
        to?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  title: string;
  /**
   * Lowercase letters, digits and hyphens, e.g. "a2-b1".
   */
  slug: string;
  levelFrom: 'A1' | 'A2' | 'B1' | 'B2' | 'C1';
  levelTo: 'A2' | 'B1' | 'B2' | 'C1' | 'C2';
  durationWeeks: number;
  summary?: string | null;
  /**
   * Textbooks and resources for the program.
   */
  materials?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Exactly 7 days, repeated every week. Day 1 is the day the student starts.
   */
  weekTemplate: {
    /**
     * Up to 5 activities. Leave empty for a rest day.
     */
    slots?:
      | {
          slotType: number | SlotType;
          /**
           * Empty = the slot type's default minimum.
           */
          minMinutes?: number | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  /**
   * Students see only published programs.
   */
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Kinds of daily activity (Anki, series …) that programs are built from.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slot-types".
 */
export interface SlotType {
  id: number;
  name: string;
  description?: string | null;
  /**
   * Minimum time for the slot to count as done, unless a program overrides it.
   */
  defaultMinMinutes: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "changelog".
 */
export interface Changelog {
  id: number;
  title: string;
  tag: 'feature' | 'improvement' | 'fix';
  summary: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Entries dated in the future stay hidden until then.
   */
  publishedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist-signups".
 */
export interface WaitlistSignup {
  id: number;
  email: string;
  /**
   * Where the signup came from, e.g. "landing-hero".
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenges".
 */
export interface Challenge {
  id: number;
  title: string;
  /**
   * Used in the public URL: /challenge/<slug>.
   */
  slug: string;
  /**
   * Day 1 of the challenge, in the time zone below.
   */
  startDate: string;
  /**
   * IANA name, e.g. Asia/Almaty. Days flip at local midnight.
   */
  timeZone: string;
  durationDays: number;
  dailyMinutes: number;
  blockDays: number;
  /**
   * Only public challenges (and their days) are visible to visitors.
   */
  isPublic?: boolean | null;
  /**
   * What counts and what does not (allowed / not allowed content).
   */
  rules?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Exactly one video per block: durationDays / blockDays items, in block order.
   */
  videos?:
    | {
        title: string;
        youtubeUrl?: string | null;
        publishedAt?: string | null;
        /**
         * Retro: what worked.
         */
        retroWorked?: string | null;
        /**
         * Retro: what to drop.
         */
        retroDropped?: string | null;
        /**
         * Retro: what to change.
         */
        retroChange?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-days".
 */
export interface ChallengeDay {
  id: number;
  challenge: number | Challenge;
  /**
   * 1…durationDays of the challenge.
   */
  dayNumber: number;
  minutes: number;
  notes?: string | null;
  /**
   * Set when the day is closed. Only closed days count towards progress.
   */
  closedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Задания, из которых собираются планы программ. Студенты видят копии, не эти записи.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-pool".
 */
export interface TaskPool {
  id: number;
  level: 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';
  /**
   * К какому занятию относится задание (необязательно).
   */
  slotType?: (number | null) | SlotType;
  /**
   * Для списков Мурада, студентам не показывается.
   */
  title: string;
  /**
   * Изменения попадут только в новые планы
   */
  text: {
    ru: string;
    en?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Задания по неделям и дням. При назначении программы студенту план копируется ему (018).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-plan-items".
 */
export interface ProgramPlanItem {
  id: number;
  program: number | Program;
  week: number;
  day: number;
  order: number;
  task: number | TaskPool;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-codes".
 */
export interface AuthCode {
  id: number;
  email: string;
  codeHash: string;
  expiresAt: string;
  attempts?: number | null;
  requestIp?: string | null;
  delivered?: boolean | null;
  consumedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'changelog';
        value: number | Changelog;
      } | null)
    | ({
        relationTo: 'waitlist-signups';
        value: number | WaitlistSignup;
      } | null)
    | ({
        relationTo: 'challenges';
        value: number | Challenge;
      } | null)
    | ({
        relationTo: 'challenge-days';
        value: number | ChallengeDay;
      } | null)
    | ({
        relationTo: 'slot-types';
        value: number | SlotType;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'task-pool';
        value: number | TaskPool;
      } | null)
    | ({
        relationTo: 'program-plan-items';
        value: number | ProgramPlanItem;
      } | null)
    | ({
        relationTo: 'enrollments';
        value: number | Enrollment;
      } | null)
    | ({
        relationTo: 'auth-codes';
        value: number | AuthCode;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  name?: T;
  invitedAt?: T;
  locale?: T;
  addressForm?: T;
  enrollments?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "changelog_select".
 */
export interface ChangelogSelect<T extends boolean = true> {
  title?: T;
  tag?: T;
  summary?: T;
  body?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist-signups_select".
 */
export interface WaitlistSignupsSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenges_select".
 */
export interface ChallengesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  startDate?: T;
  timeZone?: T;
  durationDays?: T;
  dailyMinutes?: T;
  blockDays?: T;
  isPublic?: T;
  rules?: T;
  videos?:
    | T
    | {
        title?: T;
        youtubeUrl?: T;
        publishedAt?: T;
        retroWorked?: T;
        retroDropped?: T;
        retroChange?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-days_select".
 */
export interface ChallengeDaysSelect<T extends boolean = true> {
  challenge?: T;
  dayNumber?: T;
  minutes?: T;
  notes?: T;
  closedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slot-types_select".
 */
export interface SlotTypesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  defaultMinMinutes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  levelFrom?: T;
  levelTo?: T;
  durationWeeks?: T;
  summary?: T;
  materials?: T;
  weekTemplate?:
    | T
    | {
        slots?:
          | T
          | {
              slotType?: T;
              minMinutes?: T;
              id?: T;
            };
        id?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-pool_select".
 */
export interface TaskPoolSelect<T extends boolean = true> {
  level?: T;
  slotType?: T;
  title?: T;
  text?:
    | T
    | {
        ru?: T;
        en?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-plan-items_select".
 */
export interface ProgramPlanItemsSelect<T extends boolean = true> {
  program?: T;
  week?: T;
  day?: T;
  order?: T;
  task?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  student?: T;
  placement?:
    | T
    | {
        test?: T;
        cefr?: T;
        takenAt?: T;
        testName?: T;
        scoreText?: T;
        exam?: T;
        score?: T;
        note?: T;
      };
  program?: T;
  status?: T;
  assignedAt?: T;
  startDate?: T;
  timezone?: T;
  pauses?:
    | T
    | {
        from?: T;
        to?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-codes_select".
 */
export interface AuthCodesSelect<T extends boolean = true> {
  email?: T;
  codeHash?: T;
  expiresAt?: T;
  attempts?: T;
  requestIp?: T;
  delivered?: T;
  consumedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}